# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generateData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('sexe', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(default=1)),
                ('alpha2', models.CharField(max_length=2, unique=True)),
                ('alpha3', models.CharField(max_length=2, unique=True)),
                ('nom_en_gb', models.CharField(max_length=45)),
                ('nom_fr_fr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Prenoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=25)),
                ('sexe', models.CharField(max_length=1)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateData.Pays')),
            ],
        ),
        migrations.AddField(
            model_name='noms',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generateData.Pays'),
        ),
    ]
